### PR TITLE
Update environment

### PR DESCRIPTION
**Pull request by rmcolq**
After working through the guidelines on https://artic.network/ebov/ebov-bioinformatics-sop.html with the new versioned environment file I found a couple of updates were needed:
- newer version of `porechop` (as per previous environment file)
- include `fieldbioinformatics` repository (again as per previous environment file, looks like this may once have been pulled within git and installed separately)

I also found that I had to comment out the lines for `iqtree`, `datrie` and `phyml` to get the environment to build on mac (although these three were not required for the above sop).

### CODE REVIEW

**Comment by nickloman** [comment]
We need iqtree for the phylogenetics SOP, so it would be good if this can be fixed before merging.

I had to make a change to demultiplex.py to make it work with @arambaut's fork of Porechop, which seems broken if you don't include --native_barcodes as a flag now.

**Comment by rmcolq** [comment]
OK, I'll have a fiddle with `iqtree` then

**Comment by rmcolq** [comment]
Now updated with versions as required

**Comment by nickloman** [comment]
That's great, works for me on Mac!

**Pull request merged**
